# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: p2p.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'p2p.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tp2p.proto\" \n\x0b\x66ileRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\"\x1f\n\tfileBytes\x12\x12\n\nfile_bytes\x18\x01 \x01(\x0c\x32\x30\n\x07Greeter\x12%\n\x07getFile\x12\x0c.fileRequest\x1a\n.fileBytes\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=13
  _globals['_FILEREQUEST']._serialized_end=45
  _globals['_FILEBYTES']._serialized_start=47
  _globals['_FILEBYTES']._serialized_end=78
  _globals['_GREETER']._serialized_start=80
  _globals['_GREETER']._serialized_end=128
# @@protoc_insertion_point(module_scope)
