control:
  port: 8000 # Port to listen for incoming control messages
peer:
  port: 8001 # Port to listen for incoming data or to request data
auth:
  token: "secret" # Token to authenticate


