control:
  port: 8000 # Port to listen for incoming control messages
  seed: 781 # Seed to generate the random number
peer:
  port: 8001 # Port to listen for incoming data or to request data
  ttl: 900 # Time to live in seconds


