# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import p2p_pb2 as p2p__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in p2p_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GreeterStub(object):
    """Servicio de autenticacion (Connect, Disconnet)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.join = channel.unary_unary(
                '/Greeter/join',
                request_serializer=p2p__pb2.connectionData.SerializeToString,
                response_deserializer=p2p__pb2.connectionReply.FromString,
                _registered_method=True)
        self.leave = channel.unary_unary(
                '/Greeter/leave',
                request_serializer=p2p__pb2.disconnectionData.SerializeToString,
                response_deserializer=p2p__pb2.disconnectionReply.FromString,
                _registered_method=True)


class GreeterServicer(object):
    """Servicio de autenticacion (Connect, Disconnet)
    """

    def join(self, request, context):
        """Join the p2p network
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def leave(self, request, context):
        """Leave the p2p network
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'join': grpc.unary_unary_rpc_method_handler(
                    servicer.join,
                    request_deserializer=p2p__pb2.connectionData.FromString,
                    response_serializer=p2p__pb2.connectionReply.SerializeToString,
            ),
            'leave': grpc.unary_unary_rpc_method_handler(
                    servicer.leave,
                    request_deserializer=p2p__pb2.disconnectionData.FromString,
                    response_serializer=p2p__pb2.disconnectionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Servicio de autenticacion (Connect, Disconnet)
    """

    @staticmethod
    def join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Greeter/join',
            p2p__pb2.connectionData.SerializeToString,
            p2p__pb2.connectionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def leave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Greeter/leave',
            p2p__pb2.disconnectionData.SerializeToString,
            p2p__pb2.disconnectionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
